version: "3.7"
services:
  mysql:
    build: ./mysql
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=${DB_DBNAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    restart: always

  php:
    build: ./php
    image: php:7.2-fpm
    volumes:
      - ./php/php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./public:/var/www/html
    restart: always

  nginx:
    build: ./nginx
    image: nginx:latest
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./public:/var/www/html
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=${DB_HOST}
    ports:
      - ${PMA_PORT}:80
    restart: always
